openapi: '3.0.2'
info:
  title: CHAT REST API
  description: REST API endpoints for managing the chat's related resources
  version: '0.0.0'
servers:
  - url: "http"
paths:
  /user/register:
    post:
      responses:
        '201':
          description: OK